version: '3.7'
networks:
  human_resource_api:
services:
    postgres:
      networks:
        - human_resource_api
      image: postgres:11.11
      restart: always
      environment: 
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
      logging:
         options:
           max-size: 10m
           max-file: "3"
      ports:
         - '5438:5432'
      volumes:
         - ./postgres-data:/var/lib/postgresql/data    